In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# showing path
path = r'C:\Users\TEDWI\OneDrive\Project 6'

In [3]:
df_store = pd.read_csv(r'C:\Users\TEDWI\OneDrive\Project 6\train.csv',index_col= False)

##Checking Store dataframe for missing values, inconsistencies and data wrangling

In [4]:
# showing first five rows of store dataframe
df_store.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [5]:
# showing last five rows of store dataframe
df_store.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [6]:
# showing the number of rows and columns in store dataframe
df_store.shape

(9800, 18)

In [7]:
#removing region column
df_store = df_store.drop(columns = ['Region'])

In [8]:
# gathering more info on store  dataframe
df_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Product ID     9800 non-null   object
 13  Category       9800 non-null   object
 14  Sub-Category   9800 non-null   object
 15  Product Name   9800 non-null   object
 16  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(14)
memory usage: 1.3+ MB

In [9]:
# descriptive statistics of store dataframe
df_store.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [10]:
# checking for missing values in store dataframe
df_store.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

## There are 11 missing values from  column postal code in the dataset.

In [11]:
# missing values subsets
df_nan = df_store[df_store['Postal Code'].isnull()== True]

In [12]:
#view missing values
df_nan

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Product ID,Category,Sub-Category,Product Name,Sales
2234,2235,CA-2018-104066,05/12/2018,10/12/2018,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5274,5275,CA-2016-162887,07/11/2016,09/11/2016,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,06/04/2017,10/04/2017,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9147,9148,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9386,9387,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,08/11/2016,12/11/2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90

In [13]:
# cleaning Postal Code column
df_store_clean = df_store[df_store['Postal Code'].isnull()== False]

In [14]:
# viewing column
df_store_clean

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [15]:
# viewing new shape
df_store_clean.shape

(9789, 17)

In [16]:
# removing na values
df_store.dropna( inplace = True)

In [17]:
df_store.dropna(subset=['Postal Code'], inplace = True)

In [18]:
# checking for duplicates
df_store_dups = df_store_clean[df_store_clean.duplicated()]

In [19]:
df_store_dups

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Product ID, Category, Sub-Category, Product Name, Sales]
Index: []

In [20]:
# changing customer name column from object type to str
df_store['Customer Name']= df_store['Customer Name'].astype('str')

no duplicates are in the dataset

In [21]:
#checking for mixed type columns in store data frame
for col in df_store_clean.columns.tolist():
  weird = (df_store_clean[[col]].applymap(type) != df_store_clean[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_store_clean[weird]) > 0:
    print (col)

In [22]:
# remove what is below

In [23]:
sorted(df_store['Postal Code'].unique())

[1040.0,
 1453.0,
 1752.0,
 1810.0,
 1841.0,
 1852.0,
 1915.0,
 2038.0,
 2138.0,
 2148.0,
 2149.0,
 2151.0,
 2169.0,
 2740.0,
 2886.0,
 2895.0,
 2908.0,
 2920.0,
 3060.0,
 3301.0,
 3820.0,
 4240.0,
 4401.0,
 6010.0,
 6040.0,
 6360.0,
 6450.0,
 6457.0,
 6460.0,
 6484.0,
 6708.0,
 6810.0,
 6824.0,
 7002.0,
 7011.0,
 7017.0,
 7036.0,
 7050.0,
 7055.0,
 7060.0,
 7090.0,
 7109.0,
 7501.0,
 7601.0,
 7960.0,
 8302.0,
 8360.0,
 8401.0,
 8701.0,
 8861.0,
 8901.0,
 10009.0,
 10011.0,
 10024.0,
 10035.0,
 10550.0,
 10701.0,
 10801.0,
 11520.0,
 11550.0,
 11561.0,
 11572.0,
 11757.0,
 12180.0,
 13021.0,
 13440.0,
 13501.0,
 13601.0,
 14215.0,
 14304.0,
 14609.0,
 14701.0,
 16602.0,
 17403.0,
 17602.0,
 18018.0,
 18103.0,
 19013.0,
 19120.0,
 19134.0,
 19140.0,
 19143.0,
 19601.0,
 19711.0,
 19805.0,
 19901.0,
 20016.0,
 20707.0,
 20735.0,
 20852.0,
 20877.0,
 21044.0,
 21215.0,
 21740.0,
 22153.0,
 22204.0,
 22304.0,
 22801.0,
 22901.0,
 22980.0,
 23223.0,
 23320.0,
 23434.0,
 23464.0,
 23602.0,
 23666.0,
 24153.0,
 26003.0,
 27217.0,
 27360.0,
 27405.0,
 27511.0,
 27514.0,
 27534.0,
 27604.0,
 27707.0,
 27834.0,
 27893.0,
 28027.0,
 28052.0,
 28110.0,
 28205.0,
 28314.0,
 28403.0,
 28540.0,
 28601.0,
 28806.0,
 29203.0,
 29406.0,
 29464.0,
 29483.0,
 29501.0,
 29730.0,
 30062.0,
 30076.0,
 30080.0,
 30318.0,
 30328.0,
 30344.0,
 30605.0,
 31088.0,
 31204.0,
 31907.0,
 32114.0,
 32127.0,
 32137.0,
 32174.0,
 32216.0,
 32303.0,
 32503.0,
 32712.0,
 32725.0,
 32771.0,
 32839.0,
 32935.0,
 33012.0,
 33021.0,
 33023.0,
 33024.0,
 33030.0,
 33063.0,
 33065.0,
 33068.0,
 33134.0,
 33142.0,
 33161.0,
 33178.0,
 33180.0,
 33311.0,
 33317.0,
 33319.0,
 33407.0,
 33433.0,
 33437.0,
 33445.0,
 33458.0,
 33614.0,
 33710.0,
 33801.0,
 34741.0,
 34952.0,
 35244.0,
 35401.0,
 35601.0,
 35630.0,
 35810.0,
 36116.0,
 36608.0,
 36830.0,
 37042.0,
 37064.0,
 37075.0,
 37087.0,
 37130.0,
 37167.0,
 37211.0,
 37421.0,
 37604.0,
 37620.0,
 37918.0,
 38109.0,
 38134.0,
 38301.0,
 38401.0,
 38671.0,
 39212.0,
 39401.0,
 39503.0,
 40214.0,
 40324.0,
 40475.0,
 41042.0,
 42071.0,
 42104.0,
 42301.0,
 42420.0,
 43017.0,
 43055.0,
 43123.0,
 43130.0,
 43229.0,
 43302.0,
 43402.0,
 43615.0,
 44035.0,
 44052.0,
 44060.0,
 44105.0,
 44107.0,
 44134.0,
 44221.0,
 44240.0,
 44256.0,
 44312.0,
 45011.0,
 45014.0,
 45231.0,
 45373.0,
 45503.0,
 46060.0,
 46142.0,
 46203.0,
 46226.0,
 46350.0,
 46368.0,
 46514.0,
 46544.0,
 46614.0,
 47150.0,
 47201.0,
 47362.0,
 47374.0,
 47401.0,
 47905.0,
 48066.0,
 48073.0,
 48104.0,
 48126.0,
 48127.0,
 48146.0,
 48180.0,
 48183.0,
 48185.0,
 48187.0,
 48205.0,
 48227.0,
 48234.0,
 48237.0,
 48307.0,
 48310.0,
 48601.0,
 48640.0,
 48858.0,
 48911.0,
 49201.0,
 49423.0,
 49505.0,
 50315.0,
 50322.0,
 50701.0,
 52001.0,
 52240.0,
 52302.0,
 52402.0,
 52601.0,
 53081.0,
 53132.0,
 53142.0,
 53186.0,
 53209.0,
 53214.0,
 53711.0,
 54302.0,
 54401.0,
 54601.0,
 54703.0,
 54880.0,
 54915.0,
 55016.0,
 55044.0,
 55106.0,
 55113.0,
 55122.0,
 55124.0,
 55125.0,
 55369.0,
 55407.0,
 55433.0,
 55901.0,
 56301.0,
 56560.0,
 57103.0,
 57401.0,
 57701.0,
 58103.0,
 59102.0,
 59405.0,
 59601.0,
 59715.0,
 59801.0,
 60004.0,
 60016.0,
 60025.0,
 60035.0,
 60067.0,
 60068.0,
 60076.0,
 60089.0,
 60090.0,
 60098.0,
 60126.0,
 60174.0,
 60188.0,
 60201.0,
 60302.0,
 60423.0,
 60440.0,
 60441.0,
 60462.0,
 60477.0,
 60505.0,
 60540.0,
 60543.0,
 60610.0,
 60623.0,
 60653.0,
 61032.0,
 61107.0,
 61604.0,
 61701.0,
 61761.0,
 61821.0,
 61832.0,
 62301.0,
 62521.0,
 63116.0,
 63122.0,
 63301.0,
 63376.0,
 64055.0,
 64118.0,
 65109.0,
 65203.0,
 65807.0,
 66062.0,
 66212.0,
 66502.0,
 67212.0,
 67846.0,
 68025.0,
 68104.0,
 68701.0,
 68801.0,
 70065.0,
 70506.0,
 70601.0,
 71111.0,
 71203.0,
 71603.0,
 71854.0,
 71901.0,
 72032.0,
 72209.0,
 72401.0,
 72701.0,
 72756.0,
 72762.0,
 73034.0,
 73071.0,
 73120.0,
 73505.0,
 74012.0,
 74133.0,
 74403.0,
 75002.0,
 75007.0,
 75019.0,
 75023.0,
 75034.0,
 75043.0,
 75051.0,
 75056.0,
 75061.0,
 75080.0,
 75081.0,
 75104.0,
 75150.0,
 75217.0,
 75220.0,
 75701.0,
 76017.0,
 76021.0,
 76051.0,
 76063.0,
 76106.0,
 76117.0,
 76248.0,
 76706.0,
 76903.0,
 77036.0,
 77041.0,
 77070.0,
 77095.0,
 77301.0,
 77340.0,
 77489.0,
 77506.0,
 77520.0,
 77536.0,
 77573.0,
 77581.0,
 77590.0,
 77642.0,
 77705.0,
 77803.0,
 77840.0,
 78041.0,
 78207.0,
 78415.0,
 78501.0,
 78521.0,
 78539.0,
 78550.0,
 78577.0,
 78664.0,
 78666.0,
 78745.0,
 79109.0,
 79424.0,
 79605.0,
 79762.0,
 79907.0,
 80004.0,
 80013.0,
 80020.0,
 80022.0,
 80027.0,
 80112.0,
 80122.0,
 80134.0,
 80219.0,
 80229.0,
 80501.0,
 80525.0,
 80538.0,
 80634.0,
 80906.0,
 81001.0,
 82001.0,
 83201.0,
 83301.0,
 83501.0,
 83605.0,
 83642.0,
 83704.0,
 84020.0,
 84041.0,
 84043.0,
 84057.0,
 84062.0,
 84084.0,
 84106.0,
 84107.0,
 84321.0,
 84604.0,
 85023.0,
 85204.0,
 85224.0,
 85234.0,
 85254.0,
 85281.0,
 85301.0,
 85323.0,
 85345.0,
 85364.0,
 85635.0,
 85705.0,
 86442.0,
 87105.0,
 87124.0,
 87401.0,
 87505.0,
 88001.0,
 88101.0,
 88220.0,
 89015.0,
 89031.0,
 89115.0,
 89431.0,
 89502.0,
 90004.0,
 90008.0,
 90032.0,
 90036.0,
 90045.0,
 90049.0,
 90278.0,
 90301.0,
 90503.0,
 90604.0,
 90640.0,
 90660.0,
 90712.0,
 90805.0,
 91104.0,
 91360.0,
 91505.0,
 91730.0,
 91761.0,
 91767.0,
 91776.0,
 91911.0,
 91941.0,
 92020.0,
 92024.0,
 92025.0,
 92037.0,
 92054.0,
 92105.0,
 92236.0,
 92253.0,
 92307.0,
 92345.0,
 92374.0,
 92399.0,
 92404.0,
 92503.0,
 92530.0,
 92553.0,
 92563.0,
 92592.0,
 92627.0,
 92630.0,
 92646.0,
 92672.0,
 92677.0,
 92683.0,
 92691.0,
 92704.0,
 92804.0,
 93010.0,
 93030.0,
 93101.0,
 93277.0,
 93309.0,
 93405.0,
 93454.0,
 93534.0,
 93727.0,
 93905.0,
 94061.0,
 94086.0,
 94109.0,
 94110.0,
 94122.0,
 94403.0,
 94509.0,
 94513.0,
 94521.0,
 94526.0,
 94533.0,
 94568.0,
 94591.0,
 94601.0,
 95037.0,
 95051.0,
 95123.0,
 95207.0,
 95336.0,
 95351.0,
 95610.0,
 95616.0,
 95661.0,
 95687.0,
 95695.0,
 95823.0,
 95928.0,
 96003.0,
 97030.0,
 97123.0,
 97206.0,
 97224.0,
 97301.0,
 97405.0,
 97477.0,
 97504.0,
 97756.0,
 98002.0,
 98006.0,
 98026.0,
 98031.0,
 98042.0,
 98052.0,
 98059.0,
 98103.0,
 98105.0,
 98115.0,
 98198.0,
 98208.0,
 98226.0,
 98270.0,
 98502.0,
 98632.0,
 98661.0,
 99207.0,
 99301.0]

In [24]:
df_store= df_store[df_store['Postal Code'].notna()]
df_store['Postal Code'].isna().any()

False

In [25]:
df_store['Postal Code']=df_store['Postal Code'].astype(int)

In [31]:
df_store = df_store.drop(columns = ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment','Country',
           'City', 'State', 'Product ID', 'Category', 'Sub-Category', 'Product Name'], axis=1)

In [32]:
df_store.head()

   Postal Code     Sales
0        42420  261.9600
1        42420  731.9400
2        90036   14.6200
3        33311  957.5775
4        33311   22.3680

no mixed type data is in the dataset

In [33]:
# exporting file as a pickle
df_store_clean.to_pickle(os.path.join(path, 'df_store_new.pkl'))